---
- hosts: all
  tasks:
    - name: Template a file to /etc/ssh/sshd_config
      template:
      src: /templates/sshd_config.j2
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: '0644'